podTemplate(cloud: 'kubernetes', containers: [
    containerTemplate(
        args: '9999999', 
        command: 'sleep', 
        image: 'bitnami/git', 
        livenessProbe: containerLivenessProbe(execArgs: '', failureThreshold: 0, initialDelaySeconds: 0, periodSeconds: 0, successThreshold: 0, timeoutSeconds: 0), 
        name: 'git', 
        resourceLimitCpu: '', 
        resourceLimitEphemeralStorage: '', 
        resourceLimitMemory: '', 
        resourceRequestCpu: '', 
        resourceRequestEphemeralStorage: '',
        resourceRequestMemory: '', 
        workingDir: '/home/jenkins/agent'), 
    containerTemplate(
        args: '9999999', 
        command: 'sleep', 
        image: 'node:18.20-alpine', 
        livenessProbe: containerLivenessProbe(execArgs: '', failureThreshold: 0, initialDelaySeconds: 0, periodSeconds: 0, successThreshold: 0, timeoutSeconds: 0), 
        name: 'node', 
        resourceLimitCpu: '', 
        resourceLimitEphemeralStorage: '', 
        resourceLimitMemory: '', 
        resourceRequestCpu: '', 
        resourceRequestEphemeralStorage: '',
        resourceRequestMemory: '', 
        workingDir: '/home/jenkins/agent'), 
    containerTemplate(
        args: '9999999', 
        command: 'sleep', 
        image: 'harbor.thepostway.com/google/kaniko-project/executor:v1.23.2-debug', 
        livenessProbe: containerLivenessProbe(execArgs: '', failureThreshold: 0, initialDelaySeconds: 0, periodSeconds: 0, successThreshold: 0, timeoutSeconds: 0), 
        name: 'kaniko', 
        resourceLimitCpu: '', 
        resourceLimitEphemeralStorage: '', 
        resourceLimitMemory: '', 
        resourceRequestCpu: '', 
        resourceRequestEphemeralStorage: '', 
        resourceRequestMemory: '', 
        workingDir: '/home/jenkins/agent'),
    containerTemplate(
        args: '9999999', 
        command: 'sleep', 
        image: 'fluxcd/helm-operator:1.4.4', 
        livenessProbe: containerLivenessProbe(execArgs: '', failureThreshold: 0, initialDelaySeconds: 0, periodSeconds: 0, successThreshold: 0, timeoutSeconds: 0), 
        name: 'helm', 
        resourceLimitCpu: '', 
        resourceLimitEphemeralStorage: '', 
        resourceLimitMemory: '', 
        resourceRequestCpu: '', 
        resourceRequestEphemeralStorage: '', 
        resourceRequestMemory: '', 
        workingDir: '/home/jenkins/agent')
    ], 
    inheritFrom: ' ', 
    namespace: 'cicd', 
    volumes: [
        secretVolume(defaultMode: '', mountPath: '/kaniko/.docker', optional: false, secretName: 'kaniko-secret')
    ]) {
    node(POD_LABEL) {

        def gitBranch = 'develop'
        def cmd = ''
        def mode = 'develop'
        def tag = 'latest'
        def gitRevision = ''
        def workspace = ''

        stage("git clone") {
            container("git") {
                script {
                    try {
                        // get workspace in jenkins agent
                        workspace = pwd()

                        // get data from webhook
                        if (env.gitlabBranch != null) {
                            gitBranch = "${env.gitlabBranch}";
                        } else {
                            gitBranch = "${gitBranch}";
                        }

                        // check mode in develop, staging or production
                        if (gitBranch.indexOf("develop") > -1 || gitBranch.indexOf("feature") > -1) {
                            mode = 'develop'
                        } else if (gitBranch.indexOf("release") > -1 || gitBranch.indexOf("hotfix") > -1) {
                            mode = 'staging'
                        } else if (gitBranch.indexOf("master") > -1 || gitBranch.indexOf("main") > -1) {
                            mode = 'production'
                        }
                    } catch (ex) {
                        gitBranch = "develop";
                        mode = 'develop';
                    }

                    // git clone code
                    git branch: "${gitBranch}", credentialsId: "${gitCred}", url: "${gitUrl}"

                    // add git safe directory
                    sh "git config --global --add safe.directory ${workspace}"

                    // get git revision
                    gitRevision = sh(script: "git log -n 1 --pretty=format:'%H'", returnStdout: true).substring(0, 16)

                    if (mode == 'production') {
                        tag = sh(script: 'git tag --points-at HEAD | tail -1', returnStdout: true)
                        tag = tag.trim()
                    }
                }
            }
        }

        stage("pre-build") {
            container("node") {
                script {
                    ansiColor('xterm') {
                        try {
                            cmd = [
                                "install",
                                "--verbose",
                            ].join(' ')
                            sh "npm ${cmd}"
                        } catch (ex) {
                            cleanWs()
                            error ex.getMessage()
                        }
                    }
                }
            }
        }

        stage("build") {
            container("node") {
                script {
                    sh "npm run build"
                }
            }
        }

        stage('build by kaniko') {
        }

        stage('deploy') {
        }
    }
}
