sonar.projectKey=simpitec-analytics-spend-web
sonar.host.url=https://sonarqube.thepostway.com
sonar.token=squ_5c93bef2d810f9309c869b52728b92450a6a7cae
sonar.sourceEncoding=UTF-8
sonar.sources=.
# sonar.exclusions=**/*.spec.ts,**/*.html,**/*.scss
sonar.inclusions=**/*.js,**/*.css
